"""EdgeFinder v2 — Pydantic domain models.

These are in-memory domain objects passed between layers.
They are distinct from the SQLAlchemy ORM models in db/models.py.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ── Enums ────────────────────────────────────────────────


class Direction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"


class TradeType(str, Enum):
    DAY = "DAY"
    SWING = "SWING"


class TradeStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class MarketRegime(str, Enum):
    BULL = "bull"
    BEAR = "bear"
    SIDEWAYS = "sideways"


class SignalAction(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class TickerSource(str, Enum):
    SCANNER = "scanner"
    MANUAL = "manual"
    INJECTED = "injected"



# ── Domain Models ────────────────────────────────────────


class BarData(BaseModel):
    """A single OHLCV bar."""

    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    vwap: Optional[float] = None
    trade_count: Optional[int] = None


class Signal(BaseModel):
    """A trading signal generated by a strategy."""

    ticker: str
    action: SignalAction
    entry_price: float
    stop_loss: float
    target: float
    shares: int = 0  # 0 = let executor size
    confidence: float = 0.0  # 0-100
    trade_type: TradeType = TradeType.DAY
    strategy_name: str = ""
    indicators: dict = Field(default_factory=dict)
    metadata: dict = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def risk_per_share(self) -> float:
        return abs(self.entry_price - self.stop_loss)

    @property
    def reward_to_risk(self) -> float:
        if self.risk_per_share == 0:
            return 0.0
        return abs(self.target - self.entry_price) / self.risk_per_share


class Trade(BaseModel):
    """A paper trade (open or closed)."""

    trade_id: str
    strategy_name: str
    symbol: str
    direction: Direction
    trade_type: TradeType
    entry_price: float
    exit_price: Optional[float] = None
    shares: int
    stop_loss: float
    target: float
    confidence: float
    status: TradeStatus = TradeStatus.OPEN
    pnl_dollars: Optional[float] = None
    pnl_percent: Optional[float] = None
    r_multiple: Optional[float] = None
    exit_reason: Optional[str] = None
    market_snapshot_id: Optional[int] = None
    sentiment_score: Optional[float] = None
    sentiment_data: Optional[dict] = None
    technical_signals: Optional[dict] = None
    entry_time: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    exit_time: Optional[datetime] = None
    sequence_num: Optional[int] = None
    integrity_hash: Optional[str] = None


class MarketSnapshot(BaseModel):
    """Broad market state captured at trade time or periodically."""

    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    spy_price: float = 0.0
    spy_change_pct: float = 0.0
    qqq_price: float = 0.0
    qqq_change_pct: float = 0.0
    iwm_price: float = 0.0
    iwm_change_pct: float = 0.0
    dia_price: float = 0.0
    dia_change_pct: float = 0.0
    vix_level: float = 0.0
    market_regime: MarketRegime = MarketRegime.SIDEWAYS
    sector_performance: dict = Field(default_factory=dict)
    advance_decline_ratio: Optional[float] = None



class TickerFundamentals(BaseModel):
    """Fundamental data for a ticker."""

    symbol: str
    company_name: Optional[str] = None
    sector: Optional[str] = None
    industry: Optional[str] = None
    market_cap: Optional[float] = None
    price: Optional[float] = None
    # Fundamental ratios
    peg_ratio: Optional[float] = None
    earnings_growth: Optional[float] = None
    debt_to_equity: Optional[float] = None
    revenue_growth: Optional[float] = None
    institutional_pct: Optional[float] = None
    fcf_yield: Optional[float] = None
    price_to_tangible_book: Optional[float] = None
    short_interest: Optional[float] = None
    ev_to_ebitda: Optional[float] = None
    current_ratio: Optional[float] = None
    # Raw JSON for research deep-dive
    raw_data: Optional[dict] = None


class StrategyAccountState(BaseModel):
    """Current state of a strategy's virtual account."""

    strategy_name: str
    starting_capital: float = 5_000.00
    cash_balance: float = 5_000.00
    open_positions_value: float = 0.0
    total_equity: float = 5_000.00
    peak_equity: float = 5_000.00
    drawdown_pct: float = 0.0
    pdt_enabled: bool = False
    is_paused: bool = False
    open_positions: list[Trade] = Field(default_factory=list)

    @property
    def buying_power(self) -> float:
        """Available cash for new trades. No margin — cash only."""
        return self.cash_balance
