"""
EdgeFinder Strategy Base — ABC and Registry
=============================================
All strategies inherit from BaseStrategy and register via decorator.

Usage:
    @StrategyRegistry.register("my_strategy")
    class MyStrategy(BaseStrategy):
        ...

    strategy = StrategyRegistry.get("my_strategy")
"""

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

import pandas as pd

logger = logging.getLogger(__name__)


# ── DATA CLASSES ─────────────────────────────────────────────

@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    ticker: str
    action: str                      # "BUY" or "SELL"
    entry_price: float               # Price at decision time
    stop_loss: float
    target: float
    shares: int = 0                  # 0 = let executor size it
    confidence: float = 0.0          # 0-100
    trade_type: str = "DAY"          # "DAY" or "SWING"
    metadata: dict = field(default_factory=dict)  # Strategy-specific context
    timestamp: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    @property
    def risk_per_share(self) -> float:
        return abs(self.entry_price - self.stop_loss)

    @property
    def reward_to_risk(self) -> float:
        if self.risk_per_share == 0:
            return 0.0
        return abs(self.target - self.entry_price) / self.risk_per_share


@dataclass
class TradeNotification:
    """Notification sent to a strategy after a trade is executed or closed."""
    trade_id: str
    ticker: str
    action: str               # "BUY" or "SELL"
    entry_price: float
    exit_price: Optional[float] = None
    shares: int = 0
    pnl_dollars: Optional[float] = None
    pnl_percent: Optional[float] = None
    r_multiple: Optional[float] = None
    exit_reason: Optional[str] = None
    timestamp: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


@dataclass
class MarketRegime:
    """Current market environment classification."""
    trend: str = "unknown"           # "bull", "bear", "sideways"
    volatility: str = "normal"       # "low", "normal", "high"
    vix_level: Optional[float] = None
    spy_sma_50: Optional[float] = None
    spy_sma_200: Optional[float] = None
    spy_price: Optional[float] = None
    timestamp: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


# ── BASE STRATEGY ────────────────────────────────────────────

class BaseStrategy(ABC):
    """Abstract base class for all trading strategies.

    Subclasses must implement:
        - name: str property
        - version: str property
        - init(): setup before trading begins
        - generate_signals(bars): produce signals from market data
        - on_trade_executed(notification): handle trade execution feedback
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Unique strategy identifier (e.g., 'lynch_burry')."""
        ...

    @property
    @abstractmethod
    def version(self) -> str:
        """Strategy version string (e.g., '1.0.0')."""
        ...

    @property
    @abstractmethod
    def preferred_signals(self) -> set[str]:
        """Signal types this strategy acts on.

        Only trades containing at least one of these signal types will be
        considered.  Valid types: ema_crossover_day, ema_crossover_swing,
        rsi_oversold, rsi_overbought, macd_crossover, volume_spike.
        """
        ...

    @abstractmethod
    def init(self) -> None:
        """Setup before any trades. Load models, subscribe to data, etc."""
        ...

    @abstractmethod
    def generate_signals(
        self, bars: dict[str, pd.DataFrame]
    ) -> list[Signal]:
        """Generate trading signals from current market data.

        Args:
            bars: Dict of ticker -> DataFrame with OHLCV columns.
                  Each DataFrame contains only data available at decision time
                  (no future data).

        Returns:
            List of Signal objects (may be empty).
        """
        ...

    @abstractmethod
    def on_trade_executed(self, notification: TradeNotification) -> None:
        """Called after a trade is opened or closed.

        Use for logging, learning, or adjusting internal state.
        """
        ...

    def on_market_regime_change(self, regime: MarketRegime) -> None:
        """Optional: called when market regime changes.

        Override to adjust behavior based on market conditions.
        """
        pass

    def on_strategy_pause(self, reason: str) -> None:
        """Optional: called when auto-paused due to drawdown.

        Override to handle pause events (e.g., save state).
        """
        pass

    def get_watchlist(self) -> list[str]:
        """Return list of tickers this strategy wants data for.

        Override to dynamically select tickers. Default returns empty list,
        meaning the strategy will receive data for all arena tickers.
        """
        return []


# ── STRATEGY REGISTRY ────────────────────────────────────────

class StrategyRegistry:
    """Registry for strategy plugins. Strategies register via decorator.

    Usage:
        @StrategyRegistry.register("momentum")
        class MomentumStrategy(BaseStrategy):
            ...

        # Later:
        cls = StrategyRegistry.get("momentum")
        instance = cls()
        instance.init()
    """

    _strategies: dict[str, type[BaseStrategy]] = {}

    @classmethod
    def register(cls, name: str):
        """Decorator to register a strategy class.

        Args:
            name: Unique name for the strategy.

        Raises:
            ValueError: If name is already registered.
        """
        def decorator(strategy_cls: type[BaseStrategy]):
            if name in cls._strategies:
                raise ValueError(
                    f"Strategy '{name}' already registered by "
                    f"{cls._strategies[name].__name__}"
                )
            if not issubclass(strategy_cls, BaseStrategy):
                raise TypeError(
                    f"{strategy_cls.__name__} must inherit from BaseStrategy"
                )
            cls._strategies[name] = strategy_cls
            logger.info(f"Registered strategy: {name} ({strategy_cls.__name__})")
            return strategy_cls
        return decorator

    @classmethod
    def get(cls, name: str) -> type[BaseStrategy]:
        """Get a registered strategy class by name.

        Args:
            name: The registered strategy name.

        Returns:
            The strategy class (not an instance).

        Raises:
            KeyError: If strategy not found.
        """
        if name not in cls._strategies:
            raise KeyError(
                f"Strategy '{name}' not found. "
                f"Available: {list(cls._strategies.keys())}"
            )
        return cls._strategies[name]

    @classmethod
    def list_strategies(cls) -> dict[str, type[BaseStrategy]]:
        """Return all registered strategies."""
        return dict(cls._strategies)

    @classmethod
    def create_all(cls) -> dict[str, BaseStrategy]:
        """Instantiate and init all registered strategies.

        Returns:
            Dict of name -> initialized strategy instance.
        """
        instances = {}
        for name, strategy_cls in cls._strategies.items():
            try:
                instance = strategy_cls()
                instance.init()
                instances[name] = instance
                logger.info(f"Initialized strategy: {name} v{instance.version}")
            except Exception as e:
                logger.error(f"Failed to initialize strategy '{name}': {e}")
        return instances

    @classmethod
    def clear(cls) -> None:
        """Clear all registrations (for testing)."""
        cls._strategies.clear()
